const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../docs'),server=http.createServer((req,res)=>{try{const f=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});try{
 const context=await browser.newContext({acceptDownloads:true});context.setDefaultTimeout(10000);const base='http://127.0.0.1:'+server.address().port,errors=[];await context.addInitScript(()=>{window.showDirectoryPicker=async()=>{const r=await navigator.storage.getDirectory();return r.getDirectoryHandle('Koppelingen test',{create:true})}});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/Begin%20hier.html');await p.locator('#wm-choose').click();await p.waitForFunction(()=>Werkmap.active);
 await p.goto(base+'/Apps/Uren/Start%20Uren.html?werkruimte=eigen');await p.waitForFunction(()=>Werkmap.active);await p.evaluate(()=>{change(d=>d.entries=[{id:'wm-hours',date:'2026-09-17',client:'Testklant',project:'Testproject',description:'Werk',minutes:60,billable:true,rateCents:7500}]);$('period').value='all';render();window.originalWriter=FileSystemFileHandle.prototype.createWritable;FileSystemFileHandle.prototype.createWritable=async()=>{throw Error('Test schijf vol')};});
 await p.locator('.link-select input').check();await p.locator('#hours-invoice').click();await p.locator('.link-dialog [type=submit]').click();await p.waitForFunction(()=>document.querySelector('.link-error')?.textContent.includes('niet bewaard'));assert.equal(await p.evaluate(()=>data.entries[0].billing.status),'prepared');assert.equal(await p.evaluate(()=>data.entries[0].billing.number),undefined);await p.locator('.link-dialog [data-cancel]').click();await p.evaluate(()=>FileSystemFileHandle.prototype.createWritable=window.originalWriter);
 await p.locator('#hours-resend').click();await p.locator('.link-dialog [type=submit]').click();await p.waitForFunction(()=>document.getElementById('link-result')?.textContent.includes('Bestand bewaard'));const transfer=await p.evaluate(async()=>{const r=await(await navigator.storage.getDirectory()).getDirectoryHandle('Koppelingen test'),d=await r.getDirectoryHandle('Uren schrijven'),e=await d.getDirectoryHandle('Exports'),files=await Array.fromAsync(e.values());return {count:files.length,body:JSON.parse(await(await files[0].getFile()).text())}});assert.equal(transfer.count,1);assert.equal(transfer.body.kind,'uren-factuur');assert.equal(transfer.body.body.sources[0].id,'wm-hours');assert.match(await p.locator('#link-result a').getAttribute('href'),/werkruimte=eigen/);
 await p.locator('#export').click();await p.waitForFunction(()=>document.getElementById('wm-message').textContent.startsWith('Opgeslagen'));const hours=await p.evaluate(async()=>{const r=await(await navigator.storage.getDirectory()).getDirectoryHandle('Koppelingen test'),d=await r.getDirectoryHandle('Uren schrijven');return JSON.parse(await(await(await d.getFileHandle('gereedschapskist-uren-schrijven.json')).getFile()).text())});assert.equal(hours.entries[0].billing.status,'prepared');
 await p.goto(base+'/Apps/Ping/Start%20Ping.html?werkruimte=eigen');await p.locator('#take-hours-file').setInputFiles({name:'overdracht.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(transfer.body))});await p.waitForSelector('.link-dialog');await p.evaluate(()=>{window.oldSet=GereedschapskistMode.storage.setItem;GereedschapskistMode.storage.setItem=()=>{throw Error('Test opslag vol')}});await p.locator('.link-dialog [type=submit]').click();assert.match(await p.locator('.link-error').innerText(),/opslag vol/);assert.equal(await p.evaluate(()=>data.invoices.length),0);await p.evaluate(()=>GereedschapskistMode.storage.setItem=window.oldSet);await p.locator('.link-dialog [type=submit]').click();assert.equal(await p.evaluate(()=>data.invoices.length),1);
 // Reusing changed bytes with a stale signature fails before a draft is created.
 const damaged=structuredClone(transfer.body);damaged.body.sources[0].minutes++;await p.locator('#take-hours-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(damaged))});await p.waitForFunction(()=>document.getElementById('link-result').textContent.includes('beschadigd'));assert.equal(await p.evaluate(()=>data.invoices.length),1);
 await p.goto(base+'/Apps/Bronnenkast/Start%20Bronnenkast.html?werkruimte=eigen');await p.evaluate(()=>{change(d=>{const e=GereedschapskistExamples('Bronnenkast');Object.assign(d,e);});});await p.locator('.link-select input').first().check();await p.locator('#sources-document').click();await p.locator('.link-dialog [type=submit]').click();await p.waitForFunction(()=>document.getElementById('link-result')?.textContent.includes('Bestand bewaard'));const markdown=await p.evaluate(async()=>{const r=await(await navigator.storage.getDirectory()).getDirectoryHandle('Koppelingen test'),d=await r.getDirectoryHandle('Verzamelen'),e=await d.getDirectoryHandle('Exports'),files=await Array.fromAsync(e.values());return {name:files[0].name,text:await(await files[0].getFile()).text()}});assert(markdown.name.endsWith('.md'));
 await p.goto(base+'/Apps/Werkbank/%E2%96%B6%20Begin%20hier.html?werkruimte=eigen');await p.locator('#loose-input').setInputFiles({name:markdown.name,mimeType:'text/markdown',buffer:Buffer.from(markdown.text)});await p.waitForFunction(()=>currentRawContent.length>30);assert.equal(await p.evaluate(()=>currentRawContent),markdown.text);
 assert.deepEqual(errors,[]);console.log('OK workmap source Exports, failed write and retry, prepared state on disk, failed invoice storage atomic, corrupted transfer rejected, exported Markdown opens in Schrijven');await context.close();
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
