const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../docs'),server=http.createServer((req,res)=>{try{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const base of [`http://127.0.0.1:${server.address().port}`,'file://'+path.resolve(__dirname,'../app')]){
 const context=await browser.newContext({acceptDownloads:true}),errors=[];context.setDefaultTimeout(8000);
 async function page(tool){const p=await context.newPage();p.on('pageerror',e=>{errors.push(tool+': '+e.message);console.error('PAGE',tool,e.message)});console.log('Open',tool);await p.goto(base+'/Apps/'+tool+'/Start%20'+tool+'.html?werkruimte=eigen');return p;}
 async function download(p,action){const event=p.waitForEvent('download');await action();const dl=await event;return fs.readFileSync(await dl.path());}
 async function upload(p,id,buffer){await p.locator('#'+id+'-file').setInputFiles({name:'overdracht.json',mimeType:'application/json',buffer});await p.waitForTimeout(120);}
 const modal=p=>p.locator('.link-dialog[open]').last();const submit=p=>modal(p).locator('[type=submit]').click();
 const uren=await page('Uren');await uren.evaluate(()=>{change(d=>d.entries=[{id:'hour1',date:'2026-09-17',client:'Klant A',project:'Project A',description:'Kort overleg',minutes:1,billable:true,rateCents:6000},{id:'hour2',date:'2026-09-17',client:'Klant A',project:'Project B',description:'Onderzoek',minutes:95,billable:true,rateCents:7550},{id:'hour3',date:'2026-09-17',client:'Klant B',project:'Project B',description:'Andere klant',minutes:60,billable:true}]);$('period').value='all';render();});
 await uren.locator('.link-select input').nth(0).check();await uren.locator('.link-select input').nth(2).check();await uren.locator('#hours-invoice').click();assert.match(await uren.locator('#link-result').innerText(),/één klant/);await uren.locator('.link-select input').nth(2).uncheck();await uren.locator('.link-select input').nth(1).check();await uren.locator('#hours-invoice').click();if(!base.startsWith('file:'))await uren.screenshot({path:'/tmp/gk-hours-transfer.png',fullPage:true});console.log('hours selected');const hourBuffer=await download(uren,()=>submit(uren));console.log('hours exported');const source=JSON.parse(hourBuffer);assert.equal(source.body.sources.length,2);assert.equal(await uren.evaluate(()=>data.entries[0].billing.status),'prepared');
 await uren.locator('[data-edit=hour1]').click();assert(await uren.locator('#rate').isDisabled());await uren.locator('#cancel').click();await uren.locator('[data-copy=hour1]').click();assert(!await uren.locator('#rate').isDisabled());assert.equal(await uren.evaluate(()=>editing),null);uren.once('dialog',d=>d.accept());await uren.locator('#cancel').click();
 const ping=await page('Ping');await upload(ping,'take-hours',hourBuffer);await modal(ping).locator('[data-cancel]').click();assert.equal(await ping.evaluate(()=>data.invoices.length),0);await upload(ping,'take-hours',hourBuffer);await submit(ping);assert.equal(await ping.evaluate(()=>data.invoices.length),1);assert.equal(await ping.evaluate(()=>current().lines[0].cents),100);assert.equal(await ping.evaluate(()=>current().lines[1].cents),11954);assert.equal(await ping.evaluate(()=>totals(current()).net),12054);
 await upload(ping,'take-hours',hourBuffer);assert.equal(await ping.evaluate(()=>data.invoices.length),1);assert.match(await ping.locator('#link-result').innerText(),/al overgenomen/);
 const partial=JSON.parse(hourBuffer);partial.body.sources=partial.body.sources.slice(0,1);await upload(ping,'take-hours',Buffer.from(JSON.stringify(partial)));assert.match(await ping.locator('#link-result').innerText(),/deel van deze uren/);
 await ping.evaluate(()=>{data.business={name:'Testbedrijf',address:'Teststraat 1\n1234 AB Amsterdam',email:'test@example.com',iban:'',kvk:'12345678',vat:'NLTEST'};Object.assign(current(),{address:'Klantstraat 1\n1234 AB Utrecht',due:'2026-10-17'});persist();render();});await ping.locator('#finalize').click();await ping.locator('#final-confirm').click();await ping.waitForFunction(()=>current().state==='final');const final=await ping.evaluate(()=>structuredClone(current()));assert.equal(final.number,'2026-001');
 const ack=await download(ping,()=>ping.locator('#invoice-hours-receipt').click());await upload(uren,'hours-receipt',ack);await submit(uren);assert.equal(await uren.evaluate(()=>data.entries[0].billing.number),'2026-001');assert.equal(await uren.evaluate(()=>data.entries[0].billing.status),'invoiced');await uren.reload();assert.equal(await uren.evaluate(()=>data.entries[0].billing.status),'invoiced');assert.equal(await uren.evaluate(()=>validate(JSON.parse(JSON.stringify(data))).entries[0].billing.number),'2026-001');
 await ping.locator('#invoice-received').click();await modal(ping).locator('[name=received]').fill('2026-09-20');await modal(ping).locator('[name=paid]').check();const receipt=await download(ping,()=>submit(ping));assert.deepEqual(await ping.evaluate(()=>current()),final);
 const book=await page('Kasboek');await upload(book,'take-receipt',receipt);assert.equal(await book.locator('#amount').inputValue(),'145,85');book.once('dialog',d=>d.accept());await book.locator('#cancel').click();assert.equal(await book.evaluate(()=>data.entries.length),0);await upload(book,'take-receipt',receipt);await book.locator('#form button.primary').click();assert.equal(await book.evaluate(()=>data.entries.length),1);assert.equal(await book.evaluate(()=>data.entries[0].date),'2026-09-20');assert.equal(await book.evaluate(()=>data.entries[0].cents),14585);await upload(book,'take-receipt',receipt);assert.match(await book.locator('#link-result').innerText(),/al als ontvangen/);await book.reload();await upload(book,'take-receipt',receipt);assert.equal(await book.evaluate(()=>data.entries.length),1);assert.equal(await book.evaluate(()=>validate(JSON.parse(JSON.stringify(data))).entries[0].sourceInvoiceNumber),'2026-001');
 const planner=await page('Publicatieplanner');await planner.evaluate(()=>{change(d=>d.items=[{id:'plan1',kind:'project',title:'Sociale innovatie',date:'2026-09-17',endDate:'2026-10-15',state:'active',channel:'',text:'',notes:'',url:''}]);$('list-view').click();});await planner.locator('[data-plan-tasks]').click();await modal(planner).locator('[name=taskTitle]').fill('Buurtgesprekken');await modal(planner).locator('#plan-add-task').click();await modal(planner).locator('[name=taskTitle]').nth(1).fill('Resultaten bespreken');await modal(planner).locator('[name=taskDue]').nth(0).fill('2026-10-01');const tasks=await download(planner,()=>submit(planner));assert.equal(await planner.evaluate(()=>data.items.length),1);
 const board=await page('Projectbord');await upload(board,'take-tasks',tasks);await submit(board);assert.equal(await board.evaluate(()=>data.tasks.length),2);assert.equal(await board.evaluate(()=>data.tasks[0].due),'2026-10-01');assert.equal(await board.evaluate(()=>data.tasks[0].project),'Sociale innovatie');await upload(board,'take-tasks',tasks);assert.match(await board.locator('#link-result').innerText(),/al op dit bord/);
 const contact=await page('Contacten');await contact.evaluate(()=>change(d=>d.contacts=[{id:'contact1',name:'Mila',organization:'Stichting',role:'',email:'',phone:'',address:'',notes:'',nextDate:'2026-10-02',nextAction:'Bel over project',tags:[],conversations:[]}]));await contact.locator('[data-contact-task]').click();const contactTask=await download(contact,()=>submit(contact));await upload(board,'take-tasks',contactTask);await submit(board);assert.equal(await board.evaluate(()=>data.tasks.length),3);assert.match(await board.evaluate(()=>data.tasks[2].notes),/Mila/);assert.equal(await contact.evaluate(()=>data.contacts[0].nextAction),'Bel over project');
 const taskHours=await download(board,()=>board.locator('[data-track-hours]').first().click());await upload(uren,'hours-task',taskHours);assert.equal(await uren.locator('#project').inputValue(),'Sociale innovatie');await uren.locator('#client').fill('Klant A');await uren.locator('#hours').fill('2');await uren.locator('#rate').fill('80');await uren.locator('#form button.primary').click();assert.equal(await uren.evaluate(()=>data.entries.length),4);assert.equal(await uren.evaluate(()=>data.entries[3].rateCents),8000);await upload(uren,'hours-task',taskHours);assert.match(await uren.locator('#link-result').innerText(),/al als urenregistratie/);
 const sources=await page('Bronnenkast');await sources.evaluate(()=>change(d=>{d.name='Bronnen innovatie';d.items=[{id:'source1',title:'Samen leren',source:'Voorbeeld',url:'https://example.com/test?q=1&n=2',summary:'Een samenvatting',quote:'Samen <script>alert(1)</script>',notes:'Eigen *notitie*',category:'Onderzoek',tags:[],checked:'',favorite:false},{id:'source2',title:'Niet geselecteerd',source:'Tweede bron',url:'',summary:'',quote:'',notes:'',category:'Overig',tags:[],checked:'',favorite:false}]}));await sources.locator('.link-select input').first().check();await sources.locator('#sources-document').click();const markdown=await download(sources,()=>submit(sources));assert.match(markdown.toString(),/# Samen leren/);assert.match(markdown.toString(),/example\.com/);assert.match(markdown.toString(),/Eigen/);assert(!markdown.toString().includes('<script>'));assert(!markdown.toString().includes('Niet geselecteerd'));
 // Invalid/example files must never create records.
 const wrong=JSON.parse(receipt);wrong._gereedschapskistExample=true;await upload(book,'take-receipt',Buffer.from(JSON.stringify(wrong)));assert.match(await book.locator('#link-result').innerText(),/dezelfde werkruimte/);const invalid=JSON.parse(receipt);invalid.body.receivedOn='2026-02-30';await upload(book,'take-receipt',Buffer.from(JSON.stringify(invalid)));assert.match(await book.locator('#link-result').innerText(),/datum/);assert.equal(await book.evaluate(()=>data.entries.length),1);
 for(const p of [uren,ping,book,planner,board,contact,sources]){await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow '+p.url());}
 if(!base.startsWith('file:'))await board.screenshot({path:'/tmp/gk-tasks-mobile.png',fullPage:true});assert.deepEqual(errors,[]);await context.close();console.log('OK',base.startsWith('file:')?'offline':'web','all six links, selection, cents, prepared/final status, cancellation, duplicates, immutable invoice, metadata reload, invalid inputs, example isolation, mobile');
 }}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
