const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,process.env.GK_TEST_OFFLINE?'../app':'../docs');
const server=http.createServer((req,res)=>{try{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html;charset=utf-8');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
const collections={Contacten:'contacts',Ping:'invoices',Projectbord:'tasks',Bronnenkast:'items',Uren:'entries',Publicatieplanner:'items',Offerte:'quotes',Kasboek:'entries',Werkbank:null};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.GK_BROWSER?{executablePath:process.env.GK_BROWSER}:{})});try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},offline:!!process.env.GK_TEST_OFFLINE}),page=await ctx.newPage(),errors=[];ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.GK_TEST_OFFLINE?pathToFileURL(root+'/').href:'http://127.0.0.1:'+server.address().port+'/';
 await page.goto(base+'Begin%20hier.html');await page.waitForSelector('.start-workspace');const links=await page.locator('.grid a').evaluateAll(a=>a.map(el=>el.href));assert(links.every(url=>new URL(url).searchParams.get('werkruimte')==='voorbeeld'));
 // Follow the home cards, not a manually forced example URL.
 for(const [tool,key]of Object.entries(collections)){
  const link=links.find(url=>decodeURIComponent(url).includes('/'+tool+'/'));await page.goto(link);await page.waitForSelector('#tool-switcher');await page.waitForFunction(()=>window.BewaarAlles);await page.evaluate(()=>BewaarAlles.ready);assert.equal(await page.evaluate(()=>GereedschapskistMode.example),true,tool);
  if(key){assert(await page.evaluate(k=>data[k].length>0,key),tool+' has content');await page.evaluate(()=>validate(data));}else{await page.waitForSelector('.tree-file');assert(await page.evaluate(()=>converterFiles.size>=2));await page.waitForSelector('#content .markdown-content h1');}
  assert(await page.locator('#file-status').innerText().then(t=>t.includes('Voorbeeld')));assert(await page.locator('#workspace-switch').isVisible());await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),tool+' example mobile width');await page.setViewportSize({width:1440,height:1000});if(tool==='Publicatieplanner'){fs.mkdirSync(path.resolve(__dirname,'../review-2026-09-20'),{recursive:true});await page.screenshot({path:path.resolve(__dirname,'../review-2026-09-20/rondleiding-plannen.png'),fullPage:true});}
 }
 // A stale, empty sample copy is repaired, without touching own storage.
 await page.selectOption('#tool-switcher','Contacten');await page.waitForURL('**/Contacten/**');await page.waitForFunction(()=>window.BewaarAlles);await page.evaluate(()=>BewaarAlles.ready);await page.evaluate(()=>{const k=document.querySelector('script[data-key]').dataset.key;GereedschapskistMode.storage.setItem(k,JSON.stringify({format:'contacten',version:1,contacts:[]}));});await page.reload();await page.waitForFunction(()=>data.contacts.length===2);
 const second=await ctx.newPage();await second.goto(links.find(url=>url.includes('/Uren/')));await second.waitForFunction(()=>window.BewaarAlles);await second.evaluate(()=>BewaarAlles.ready);
 await page.click('#workspace-switch');await page.waitForURL(/werkruimte=eigen/);await second.waitForURL(/werkruimte=eigen/);await page.waitForSelector('.example-mode.own',{state:'attached'});await second.close();
 // One exit applies to all tools followed through the tool switcher.
 for(const [tool,key]of Object.entries(collections)){
  if(await page.locator('#tool-switcher').inputValue()!==tool)await page.selectOption('#tool-switcher',tool);
  await page.waitForFunction(t=>document.querySelector('script[data-tool]')?.dataset.tool===t,tool);await page.waitForFunction(()=>window.BewaarAlles);await page.evaluate(()=>BewaarAlles.ready);
  assert.equal(await page.evaluate(()=>GereedschapskistMode.example),false,tool+' own');if(key)assert.equal(await page.evaluate(k=>data[k].length,key),0,tool+' empty');else assert.equal(await page.evaluate(()=>converterFiles.size),0);
 }
 // Preserve an unfinished own contact while taking another complete tour.
 await page.selectOption('#tool-switcher','Contacten');await page.waitForURL('**/Contacten/**');await page.waitForFunction(()=>window.BewaarAlles);await page.evaluate(()=>BewaarAlles.ready);await page.click('#new');await page.fill('#name','Mijn eigen contact');await page.locator('#form button.primary').click();await page.waitForFunction(()=>!document.getElementById('dialog').open);await page.click('#new');await page.fill('#name','Mijn onvoltooide contact');
 const own=await page.evaluate(()=>JSON.stringify(data));const other=await ctx.newPage();await other.goto(base+'Apps/Uren/Start%20Uren.html?werkruimte=eigen');await other.waitForSelector('#tool-switcher');await other.click('#workspace-help-toggle');await other.click('#workspace-switch');await page.waitForURL(/werkruimte=voorbeeld/);await other.close();await page.waitForFunction(()=>window.BewaarAlles);await page.evaluate(()=>BewaarAlles.ready);assert.equal(await page.evaluate(()=>data.contacts.length),2);
 assert.equal(await page.evaluate(()=>localStorage.getItem(document.querySelector('script[data-key]').dataset.key)),own);
 await page.locator('.suite-back').click();await page.waitForSelector('.start-workspace');assert((await page.locator('.grid a').first().getAttribute('href')).includes('werkruimte=voorbeeld'));
 await page.getByRole('button',{name:'Naar mijn eigen werk',exact:true}).click();await page.waitForURL(/werkruimte=eigen/);await page.waitForSelector('.start-workspace');await page.locator('.grid a[href*="/Contacten/"]').click();await page.waitForFunction(()=>window.BewaarAlles);await page.evaluate(()=>BewaarAlles.ready);assert.deepEqual(await page.evaluate(()=>data),JSON.parse(own));await page.waitForFunction(()=>document.getElementById('dialog').open);assert.equal(await page.inputValue('#name'),'Mijn onvoltooide contact');assert.equal(await page.evaluate(()=>GereedschapskistMode.example),false);
 assert.deepEqual(errors,[]);console.log('OK 9 populated home routes, stale sample repair, suite exit including second tab, 9 empty own tools, real data preserved, home/tool mode consistency'+(process.env.GK_TEST_OFFLINE?' offline':''));await ctx.close();
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
