const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,process.env.GK_TEST_WEB?'../docs':'../app'),server=http.createServer((req,res)=>{try{const p=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.GK_BROWSER?{executablePath:process.env.GK_BROWSER}:{})});try{
const ctx=await browser.newContext(),errors=[],downloads=[];ctx.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('download',d=>downloads.push(d.suggestedFilename()));p.on('dialog',d=>d.accept())});await ctx.addInitScript(()=>window.showDirectoryPicker=async()=> (await navigator.storage.getDirectory()).getDirectoryHandle('Samen Werk',{create:true}));
const base='http://127.0.0.1:'+server.address().port,p=await ctx.newPage();await p.goto(base+'/Begin%20hier.html?werkruimte=eigen');await p.getByRole('button',{name:'Nieuwe werkmap kiezen',exact:true}).click();await p.waitForFunction(()=>Werkmap.active);
async function go(t){await p.goto(base+'/Apps/'+t+'/Start%20'+t+'.html?werkruimte=eigen');await p.evaluate(()=>BewaarAlles.ready);}
await go('Contacten');await p.evaluate(()=>change(d=>d.contacts.push({id:'c1',name:'Testpersoon',organization:'Testbedrijf',role:'',email:'test@example.org',phone:'',address:'Teststraat 1',notes:'',nextDate:'',nextAction:'',tags:[],conversations:[]})));await p.evaluate(()=>BewaarAlles.flush());
await go('Ping');await p.click('#new');await p.click('#choose-contact');await p.waitForFunction(()=>document.getElementById('contact-list').options.length===1);await p.selectOption('#contact-list','c1');await p.click('#contact-apply');assert.equal(await p.locator('[data-scope="invoice"][data-key="customer"]').inputValue(),'Testbedrijf');
await p.click('#choose-contact');await p.click('#contact-new');await p.fill('#new-contact-name','Nieuw contact');await p.fill('#new-contact-org','Nieuw bedrijf');await p.locator('#new-contact-form button[type=submit]').click();await p.waitForFunction(()=>!document.getElementById('contact-picker').open);assert.equal((await p.evaluate(()=>Samenwerken.contacts())).length,2);
await p.evaluate(()=>BewaarAlles.flush());await go('Offerte');await p.evaluate(async()=>{const q=GereedschapskistExamples('Offerte').quotes[0];q.state='accepted';working=q;baseline='';renderEditor();});await p.click('#make-invoice');await p.waitForFunction(()=>document.getElementById('link-result')?.textContent.includes('Toegevoegd'));const invoices=await p.evaluate(async()=> (await BewaarAlles.readTool('Ping')).data.invoices);assert.equal(invoices.filter(i=>i.sourceQuoteId).length,1);await p.click('#make-invoice');assert.equal((await p.evaluate(async()=> (await BewaarAlles.readTool('Ping')).data.invoices)).filter(i=>i.sourceQuoteId).length,1);
await go('Publicatieplanner');await p.evaluate(()=>change(d=>d.items.push({id:'p1',kind:'project',title:'Project A',channel:'',state:'idea',date:'2026-10-01',endDate:'',text:'',notes:'',url:''})));await p.click('[data-plan-tasks="p1"]');await p.fill('[name=taskTitle]','Doe iets');await p.locator('.link-dialog [type=submit]').click();await p.waitForFunction(()=>!document.querySelector('.link-dialog[open]'));
const tasks=await p.evaluate(async()=> (await BewaarAlles.readTool('Projectbord')).data.tasks);assert.equal(tasks.length,1);assert.equal(tasks[0].projectId,'p1');
await p.evaluate(()=>BewaarAlles.flush());await go('Projectbord');assert.equal(await p.locator('[data-track-hours]').count(),1);await p.click('[data-track-hours]');await p.waitForFunction(()=>document.getElementById('link-result')?.textContent.includes('Toegevoegd'));await p.evaluate(()=>BewaarAlles.flush());await go('Uren');await p.waitForFunction(()=>document.getElementById('dialog').open).catch(async e=>{console.log(await p.locator('body').innerText(),errors);throw e;});assert.equal(await p.inputValue('#description'),'Doe iets');assert.equal(await p.inputValue('#project'),'Project A');await p.fill('#client','Testbedrijf');await p.fill('#hours','2');await p.fill('#rate','75');await p.locator('#form button.primary').click();await p.waitForFunction(()=>!document.getElementById('dialog').open).catch(async e=>{console.log(await p.locator('dialog').innerText(),await p.locator('#toast').innerText(),errors);throw e;});assert.equal(await p.evaluate(()=>data.entries[0].projectId),'p1');assert.equal(await p.evaluate(()=>data.entries[0].contactId),'c1');
await p.locator('.link-select input').check();await p.click('#hours-invoice');await p.locator('.link-dialog [type=submit]').click();await p.waitForFunction(()=>!document.querySelector('.link-dialog[open]'));const withHours=await p.evaluate(async()=> (await BewaarAlles.readTool('Ping')).data.invoices.find(i=>i.timeSources));assert.equal(withHours.lines[0].cents,15000);
await p.evaluate(async()=>{await Samenwerken.send('factuur-ontvangst',{invoiceId:'final1',number:'2026-001',issuer:{name:'Mijn Bedrijf',kvk:'',vat:''},customer:'Testbedrijf',cents:18150,receivedOn:'2026-10-01'},'Kasboek','r1')});assert.equal(await p.evaluate(async()=> (await BewaarAlles.readTool('Kasboek')).data.entries[0].cents),18150);
assert.match(await p.evaluate(async()=>{try{await Samenwerken.send('factuur-ontvangst',{invoiceId:'final1',number:'2026-001',issuer:{name:'Mijn Bedrijf',kvk:'',vat:''},customer:'Testbedrijf',cents:18150,receivedOn:'2026-10-01'},'Kasboek','r1')}catch(e){return e.message}}),/al als ontvangen/);
const contactsTab=await ctx.newPage();await contactsTab.goto(base+'/Apps/Contacten/Start%20Contacten.html?werkruimte=eigen');await contactsTab.evaluate(()=>BewaarAlles.ready);await contactsTab.click('#new');await contactsTab.fill('#name','Half ingevuld contact');
await p.evaluate(()=>BewaarAlles.updateTool('Contacten',d=>d.contacts.push({id:'live-contact',name:'Via andere tool',organization:'',role:'',email:'',phone:'',address:'',notes:'',nextDate:'',nextAction:'',tags:[],conversations:[]})));
assert.equal(await contactsTab.evaluate(()=>data.contacts.some(c=>c.id==='live-contact')),true);assert.equal(await contactsTab.inputValue('#name'),'Half ingevuld contact');assert.equal(await contactsTab.locator('#dialog').evaluate(d=>d.open),true);
await contactsTab.evaluate(()=>BewaarAlles.flush());await contactsTab.close();
await p.evaluate(()=>Samenwerken.document('Bronnen.md','# Bronnen\n\nEigen notities'));assert.equal(await p.evaluate(async()=> (await BewaarAlles.readTool('Werkbank')).documents[0].content),'# Bronnen\n\nEigen notities');await p.evaluate(()=>BewaarAlles.save());assert.equal(downloads.length,0);assert.deepEqual(errors,[]);console.log('OK contacts, create contact, quote invoice duplicate, project tasks, task hours, shared IDs, hours invoice, payment duplicate, sources document, active target with pending form, single save without downloads');
await ctx.close();}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
