// Run with NODE_PATH pointing to Playwright. No changes to a user's browser profile.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'../docs');
const server=http.createServer((req,res)=>{try{const file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];let context;
const open=async folder=>{if(context)await context.close();context=await browser.newContext({acceptDownloads:true});const p=await context.newPage();p.on('pageerror',e=>errors.push(folder+': '+e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(folder+': '+m.text());});await p.goto(base+'/Apps/'+folder+'/'+encodeURIComponent(folder==='Werkbank'?'▶ Begin hier.html':`Start ${folder}.html`)+'?werkruimte=eigen');await p.waitForSelector('#file-status');return p;};
const textHas=async(p,selector,text)=>{await p.waitForFunction(([s,t])=>document.querySelector(s)?.textContent.includes(t),[selector,text]);};
const file=(name,data)=>({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
try{
 // Every modal retains typed input if the user cancels dismissal via Escape.
 for(const [folder,dialog,field] of [['Contacten','dialog','name'],['Projectbord','edit','title'],['Uren','dialog','client'],['Bronnenkast','dialog','title'],['Publicatieplanner','dialog','title'],['Kasboek','dialog','party']]){
  const p=await open(folder);await p.locator('#new').click();await p.locator('#'+field).fill('Onbewaarde invoer');p.once('dialog',d=>d.dismiss());await p.keyboard.press('Escape');assert(await p.locator('#'+dialog).evaluate(e=>e.open),folder+' Escape retained');assert.equal(await p.locator('#'+field).inputValue(),'Onbewaarde invoer');p.once('dialog',d=>d.accept());await p.locator('#cancel').click();assert.equal(await p.locator('#'+dialog).evaluate(e=>e.open),false);console.log('OK Escape and cancel protection',folder);
 }
 let p=await open('Contacten');await p.locator('#new').click();await p.locator('#name').fill('Test Klant');await p.locator('#organization').fill('Test Organisatie');await p.locator('#address').fill('Teststraat 12\n1234 AB Teststad');await p.locator('#form button.primary').click();const contacts=await p.evaluate(()=>data);assert.equal(contacts.contacts[0].address,'Teststraat 12\n1234 AB Teststad');await p.locator('#compact-view').click();assert(await p.locator('#cards').evaluate(e=>e.classList.contains('compact')));
 await p.locator('[data-conversation]').click();await p.locator('#conversation-text').fill('Belangrijke notitie');p.once('dialog',d=>d.dismiss());await p.keyboard.press('Escape');assert(await p.locator('#conversation').evaluate(e=>e.open));p.once('dialog',d=>d.accept());await p.locator('#conversation-cancel').click();
 console.log('OK contact address, list, conversation guard');
 for(const folder of ['Ping','Offerte']){
  p=await open(folder);await p.locator('#new').click();await p.locator('#choose-contact').click();await p.locator('#contact-file').setInputFiles(file('contacten.json',contacts));await p.locator('#contact-list option').waitFor({state:'attached'});await p.locator('#contact-list').selectOption(contacts.contacts[0].id);await textHas(p,'#contact-preview','Teststraat 12');await p.locator('#contact-apply').click();assert.equal(await p.locator('[data-scope="'+(folder==='Ping'?'invoice':'quote')+'"][data-key=address]').inputValue(),'Teststraat 12\n1234 AB Teststad');
  if(folder==='Offerte'){await textHas(p,'#dirty','nog niet in de offertelijst');assert.equal(await p.locator('#form details').count(),4);}
  console.log('OK invoice address transfer',folder);
 }
 p=await open('Ping');assert.doesNotMatch(await p.locator('#storage').innerText(),/Download gestart|Gegevensbestand gedownload/);await p.locator('#new').click();await p.locator('#finalize').click();await p.locator('.issue-link').filter({hasText:'Bedrijfsnaam'}).click();assert.equal(await p.evaluate(()=>document.activeElement.dataset.key),'name');assert(await p.locator('#form details').evaluate(e=>e.open));console.log('OK blank invoice state and validation field links');
 // Numbering and frozen invoice data must survive the UI and status changes.
 for(const [scope,key,value] of [['business','name','Testbedrijf'],['business','address','Teststraat 1'],['business','kvk','00000000'],['business','vat','TEST'],['invoice','customer','Testklant'],['invoice','address','Teststraat 2'],['invoice','title','Testwerk'],['invoice','deliveryDate','2026-09-17']])await p.locator(`[data-scope="${scope}"][data-key="${key}"]`).fill(value);
 await p.locator('[data-line="0"][data-key="description"]').fill('Testwerk');await p.locator('[data-line="0"][data-key="cents"]').fill('100');await p.locator('#finalize').click();await p.locator('#final-confirm').click();await p.waitForFunction(()=>data.invoices[0].state==='final');const fixed=await p.evaluate(()=>structuredClone(data.invoices[0]));assert.match(fixed.number,/^\d{4}-001$/);await p.locator('#new').click();await p.locator('#form details').evaluate(e=>e.open=true);await p.locator('[data-scope="business"][data-key="name"]').fill('Ander bedrijf');assert.deepEqual(await p.evaluate(id=>data.invoices.find(i=>i.id===id),fixed.id),fixed);assert.equal(await p.evaluate(y=>data.sequences[y],fixed.date.slice(0,4)),2);console.log('OK fixed invoice number and immutable snapshot');
 p=await open('Bronnenkast');p.once('dialog',d=>d.accept('Mijn boeken'));await p.locator('#rename-collection').click();await textHas(p,'#collection-name','Mijn boeken');await p.locator('#new').click();await p.locator('#title').fill('Een boek');await p.locator('#source').fill('Een schrijver');await p.locator('#category').fill('Literatuur & essays');await p.locator('#form button.primary').click();assert.equal(await p.evaluate(()=>validate(data).name),'Mijn boeken');assert.equal(await p.evaluate(()=>data.items[0].category),'Literatuur & essays');await p.locator('[data-category="cat:Literatuur & essays"]').click();await textHas(p,'#count','1 van 1');const legacy=await p.evaluate(()=>validate({...data,name:undefined}));assert.equal(legacy.name,'Mijn collectie');console.log('OK custom collection and categories');
 p=await open('Uren');await p.locator('#new').click();await p.locator('#client').fill('Klant');await p.locator('#project').fill('Project');await p.locator('#description').fill('Werk');await p.locator('#save-another').click();assert.equal(await p.evaluate(()=>data.entries.length),1);assert(await p.locator('#dialog').evaluate(e=>e.open));assert.equal(await p.locator('#client').inputValue(),'Klant');assert.equal(await p.locator('#description').inputValue(),'');await p.locator('#description').fill('Volgende werk');await p.locator('#form button.primary').click();await p.locator('[data-copy]').first().click();await p.locator('#form button.primary').click();assert.equal(await p.evaluate(()=>data.entries.length),3);console.log('OK repeated and copied time entries');
 p=await open('Publicatieplanner');const planning=await p.evaluate(()=>{const x=GereedschapskistExamples('Publicatieplanner');x.items=[{...x.items[0],date:'2026-09-01',endDate:'2026-09-28'}];return x;});await p.locator('#file').setInputFiles(file('planning.json',planning));await p.evaluate(()=>{month='2026-09';view='calendar';render();});assert.equal(await p.locator('.week-strip').count(),5);await p.locator('.week-strip').first().click();assert(await p.locator('#channel').isHidden());assert.equal(await p.locator('#state option[value=published]').count(),0);await p.locator('#kind').selectOption('publication');assert(await p.locator('#channel').isVisible());assert.equal(await p.locator('#state option[value=published]').count(),1);p.once('dialog',d=>d.accept());await p.locator('#cancel').click();await p.screenshot({path:'/tmp/gk-calendar.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:'/tmp/gk-calendar-mobile.png',fullPage:true});console.log('OK multiweek strips and type-specific fields');
 p=await open('Kasboek');const book=await p.evaluate(()=>GereedschapskistExamples('Kasboek'));await p.locator('#file').setInputFiles(file('mijn-kasboek.json',book));await textHas(p,'#file-status','Geopend: mijn-kasboek.json');await textHas(p,'#file-status','Geen wijzigingen sinds openen');await p.locator('[data-edit]').first().click();await p.locator('#description').fill('Gewijzigde boeking');await p.locator('#save').click();await textHas(p,'#file-status','Gewijzigd sinds openen');const original=await p.evaluate(()=>JSON.stringify(data)),totals=await p.locator('#balance').innerText();const canceled=p.waitForEvent('download');await p.locator('#export').click();await (await canceled).cancel();await textHas(p,'#file-status','Download gestart. Controleer of je bestand is opgeslagen.');assert.doesNotMatch(await p.locator('#storage').innerText(),/bestand gedownload/);const event=p.waitForEvent('download');await p.locator('#export').click();const download=await event;const saved=fs.readFileSync(await download.path());assert.deepEqual(JSON.parse(saved),JSON.parse(original));await p.reload();await textHas(p,'#file-status','mijn-kasboek.json');p.once('dialog',d=>d.accept());await p.locator('#file').setInputFiles({name:download.suggestedFilename(),mimeType:'application/json',buffer:saved});await textHas(p,'#file-status','Geen wijzigingen sinds openen');assert.equal(await p.locator('#balance').innerText(),totals);assert.deepEqual(await p.evaluate(()=>data),JSON.parse(original));console.log('OK opened file, changes, canceled download and financial round trip');
 // Large photographs are reduced locally; PDFs are never rasterized.
 await p.locator('#new').click();const png=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=2600;c.height=1800;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#111';x.font='80px Arial';x.fillText('TESTBON 123 — EUR 48,50',100,200);return c.toDataURL('image/png').split(',')[1];});
 await p.locator('#receipt-file').setInputFiles({name:'grote-bon.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await p.waitForFunction(()=>attachment&&!loading);const receipt=await p.evaluate(()=>attachment);assert.equal(receipt.mime,'image/jpeg');assert(receipt.size<=2000000);assert.equal(await p.evaluate(async()=>{const b=await createImageBitmap(new Blob([Uint8Array.from(atob(attachment.base64),c=>c.charCodeAt(0))],{type:attachment.mime}));const n=Math.max(b.width,b.height);b.close();return n;}),1800);p.once('dialog',d=>d.accept());await p.locator('#cancel').click();console.log('OK receipt resize and cancel protection');
 p=await open('Projectbord');const tasks=await p.evaluate(()=>GereedschapskistExamples('Projectbord'));await p.locator('#file').setInputFiles(file('bord.json',tasks));await textHas(p,'#file-status','bord.json');await p.locator('#sort').selectOption('deadline');assert.equal(await p.evaluate(()=>data.tasks.length),4);console.log('OK board sorting');
 p=await open('Werkbank');assert(await p.locator('.projectbar').isHidden());await p.locator('#loose-new').click();await p.locator('#wysiwygEditor').waitFor();await p.locator('#wysiwygEditor').fill('Mijn onbewaarde tekst');p.once('dialog',d=>d.dismiss());await p.locator('#loose-new').click();assert.match(await p.locator('#wysiwygEditor').innerText(),/Mijn onbewaarde tekst/);const mdEvent=p.waitForEvent('download');await p.locator('#loose-save').click();const md=await mdEvent;assert.match(fs.readFileSync(await md.path(),'utf8'),/Mijn onbewaarde tekst/);await textHas(p,'#file-status','Download gestart');assert.equal(await p.evaluate(()=>converterFiles.size),1);await p.screenshot({path:'/tmp/gk-writing.png',fullPage:false});console.log('OK writing start, immediate editor, download and protected input');
 // A narrow viewport must not cause the document to overflow.
 for(const folder of ['Ping','Offerte','Uren','Publicatieplanner','Werkbank']){p=await open(folder);await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),folder+' mobile');}
 assert.deepEqual(errors,[]);console.log('OK no browser errors');
}finally{if(context)await context.close();await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
