const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,process.env.GK_TEST_WEB?'../docs':'../app'),server=http.createServer((req,res)=>{try{const p=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.GK_BROWSER?{executablePath:process.env.GK_BROWSER}:{})});try{
const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await ctx.addInitScript(()=>window.showDirectoryPicker=async()=> (await navigator.storage.getDirectory()).getDirectoryHandle('Mijn Werk',{create:true}));
const base='http://127.0.0.1:'+server.address().port;await p.goto(base+'/Begin%20hier.html?werkruimte=eigen');await p.getByRole('button',{name:'Nieuwe werkmap kiezen',exact:true}).click();await p.waitForFunction(()=>Werkmap.active);assert.equal(await p.locator('.grid a').count(),9);assert(await p.getByRole('button',{name:'Bestaande werkmap openen',exact:true}).isHidden());assert(await p.getByRole('button',{name:'Bekijk voorbeelden',exact:true}).isHidden());
fs.mkdirSync(path.resolve(__dirname,'../review-2026-09-20'),{recursive:true});await p.screenshot({path:path.resolve(__dirname,'../review-2026-09-20/home.png'),fullPage:true});
for(const t of ['Contacten','Ping','Offerte','Uren','Publicatieplanner','Projectbord','Bronnenkast','Kasboek','Werkbank']){
 await p.goto(base+'/Apps/'+t+'/'+(t==='Werkbank'?'%E2%96%B6%20Begin%20hier.html':'Start%20'+t+'.html')+'?werkruimte=eigen');await p.waitForSelector('#tool-switcher');await p.evaluate(()=>BewaarAlles.ready);assert.equal(await p.locator('#tool-switcher option').count(),9);assert(await p.locator('#wm-backup').isVisible());const id=t==='Werkbank'?'loose-save':t==='Ping'?'save':'export';assert(await p.locator('#'+id).isHidden());await p.waitForSelector('#tool-extra-actions',{state:'attached'});
 for(const extraId of ['rename','rename-collection','csv','loose-folder']){const button=p.locator('#'+extraId);if(await button.count()){assert(await button.isHidden());await p.click('#workspace-help-toggle');assert(await button.isVisible());await p.locator('#workspace-help a').first().press('Escape');assert(await button.isHidden());}}
 if(t==='Projectbord')assert.equal(await p.locator('.add-column:visible').count(),0);
 if(t==='Uren')assert(await p.locator('#hours-invoice').isHidden());
 if(t==='Bronnenkast'){assert(await p.locator('#sources-document').isHidden());assert(await p.locator('#receive-local-links').isHidden());await p.click('#workspace-help-toggle');assert(await p.locator('#receive-local-links').isVisible());await p.click('#workspace-help-toggle');}

 if(t==='Publicatieplanner'){await p.selectOption('#kind-filter','project');assert(await p.locator('#channel-filter').isHidden());await p.screenshot({path:path.resolve(__dirname,'../review-2026-09-20/plannen.png'),fullPage:true});}
 if(t==='Contacten'){await p.click('#new');await p.fill('#name','Concept bij wisselen');await p.locator('dialog[open] .gk-save-all').click();await p.waitForFunction(()=>document.querySelector('.all-dialog-status').textContent.includes('Alles bewaard'));await p.goto(base+'/Apps/Publicatieplanner/Start%20Publicatieplanner.html?werkruimte=eigen');await p.waitForURL('**/Publicatieplanner/**');await p.selectOption('#tool-switcher','Contacten');await p.waitForFunction(()=>document.getElementById('dialog').open);assert.equal(await p.inputValue('#name'),'Concept bij wisselen');await p.evaluate(()=>document.getElementById('dialog').close());}
 await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow '+t);if(t==='Ping'||t==='Offerte'){assert(await p.locator('.preview').isHidden());await p.getByRole('tab',{name:'Voorbeeld',exact:true}).click();assert(await p.locator('.preview').isVisible());assert(await p.locator('.editor').isHidden());await p.getByRole('tab',{name:'Gegevens',exact:true}).click();assert(await p.locator('.editor').isVisible());}await p.setViewportSize({width:1440,height:1000});
}
assert.deepEqual(errors,[]);console.log('OK: 9 tool switchers, one visible save action, draft navigation, relevant filters, mobile overflow');await ctx.close();}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
