'use strict';
(()=>{
 const K=Koppelingen,chosen=new Set();
 document.addEventListener('werkbestand-geopend',()=>{chosen.clear();render()});
 function decorate(){for(const b of $('cards').querySelectorAll('[data-edit]')){const card=b.closest('article');if(card.querySelector('.link-select'))continue;const i=data.items.find(x=>x.id===b.dataset.edit),l=document.createElement('label'),c=document.createElement('input');l.className='link-select';c.type='checkbox';c.checked=chosen.has(i.id);c.setAttribute('aria-label','Selecteer bron: '+i.title);c.onchange=()=>c.checked?chosen.add(i.id):chosen.delete(i.id);l.append(c,document.createTextNode('Selecteer voor document'));card.prepend(l);}}
 const oldRender=render;render=function(){oldRender();decorate()};new MutationObserver(decorate).observe($('cards'),{childList:true});decorate();
 const md=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/([\\`*_{}\[\]()#+.!|~-])/g,'\\$1');
 K.button('Maak document','sources-document',()=>{K.ready();K.fresh();const list=data.items.filter(i=>chosen.has(i.id));if(!list.length)throw Error('Selecteer eerst bronnen op de kaarten.');K.dialog('Bronnen naar Schrijven','<p>'+list.length+' geselecteerde bronnen worden een bewerkbaar Markdown-document, inclusief links, citaten en eigen notities.</p><label>Documenttitel<input name="title" required maxlength="180" value="'+K.esc(data.name||'Mijn bronnen')+'"></label>',async form=>{K.fresh();const title=K.text(form.elements.title.value.trim(),180,true);let content='# '+md(title)+'\n\n';for(const i of list){content+='## '+md(i.title)+'\n\n';if(i.source)content+='Bron: '+md(i.source)+'\n\n';if(i.url){const url=safeURL(i.url);if(!url)throw Error('Een bron heeft een ongeldige link.');content+='[Open bron](<'+url.replace(/</g,'%3C').replace(/>/g,'%3E')+'>)\n\n';}if(i.summary)content+=md(i.summary)+'\n\n';if(i.quote)content+='### Citaat\n\n'+md(i.quote).split('\n').map(s=>'> '+s).join('\n')+'\n\n';if(i.notes)content+='### Eigen notities\n\n'+md(i.notes)+'\n\n';}const slug=title.toLocaleLowerCase('nl').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'bronnen';await K.deliver(new Blob([content],{type:'text/markdown;charset=utf-8'}),'gereedschapskist-'+(GereedschapskistMode.example?'voorbeeld-':'')+'schrijven-'+slug+'-'+K.today()+'.md','Werkbank','Kies in Schrijven Document openen en selecteer dit Markdown-bestand.');},'Document bewaren');});
})();
