'use strict';
window.Koppelingen=(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uid=()=>crypto.randomUUID(),today=()=>new Date().toLocaleDateString('sv-SE');
 const paths={Ping:'../Ping/Start%20Ping.html',Uren:'../Uren/Start%20Uren.html',Kasboek:'../Kasboek/Start%20Kasboek.html',Projectbord:'../Projectbord/Start%20Projectbord.html',Werkbank:'../Werkbank/%E2%96%B6%20Begin%20hier.html'};
 const names={Ping:'Factureren',Uren:'Uren schrijven',Kasboek:'Boekhouden',Projectbord:'Doen',Werkbank:'Schrijven'};
 const drafts=new Map();let dialogCount=0;
 function text(v,max=200,required=false){if(typeof v!=='string'||v.length>max||required&&!v.trim())throw Error('Een tekstveld ontbreekt of is te lang.');return v;}
 function integer(v,min,max){if(!Number.isSafeInteger(v)||v<min||v>max)throw Error('Een aantal of bedrag is ongeldig.');return v;}
 function date(v,required=true){text(v,10,required);if(!v&&!required)return v;if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||v<'1900-01-01'||isNaN(Date.parse(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw Error('Een datum is ongeldig.');return v;}
 function id(v){return text(v,100,true)}
 function rate(v){if(v===''||v===null||v===undefined)return null;const s=String(v).trim().replace(',','.');if(!/^\d{1,7}(\.\d{1,2})?$/.test(s))throw Error('Vul een uurtarief in met maximaal twee decimalen.');return integer(Math.round(Number(s)*100),0,100000000);}
 function vat(v){if(![0,9,21].includes(v))throw Error('Ongeldig btw-percentage.');return v;}
 function number(v){text(v,32,true);if(!/^\d{4}-\d{3,6}$/.test(v))throw Error('Ongeldig definitief factuurnummer.');return v;}
 function digest(v){text(v,64,true);if(!/^[a-f0-9]{64}$/.test(v))throw Error('Ongeldige bronverwijzing.');return v;}
 async function key(parts){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(parts))))].map(n=>n.toString(16).padStart(2,'0')).join('');}
 const signature=i=>key([i.date,i.client,i.project,i.description,i.minutes,i.rateCents,i.vat??21]);
 const euro=c=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(c/100);
 const duration=n=>Math.floor(n/60)+':'+String(n%60).padStart(2,'0');
 function timeFields(i={}){const out={};if(i.rateCents!==undefined)out.rateCents=i.rateCents===null?null:integer(i.rateCents,0,100000000);if(i.vat!==undefined)out.vat=vat(i.vat);
  for(const k of ['sourceTaskId','sourceTransferId'])if(i[k]!==undefined)out[k]=id(i[k]);
  if(i.billing!==undefined){const b=i.billing;if(!b||!['prepared','invoiced'].includes(b.status))throw Error('Ongeldige factuurstatus bij uren.');out.billing={batchId:id(b.batchId),status:b.status,signature:digest(b.signature)};if(b.status==='invoiced'){out.billing.invoiceId=id(b.invoiceId);out.billing.number=number(b.number);}}
  return out;
 }
 function cashFields(i){const out={};for(const k of ['sourceInvoiceId','sourceInvoiceNumber','sourceInvoiceKey'])if(i[k]!==undefined)out[k]=k==='sourceInvoiceNumber'?number(i[k]):k==='sourceInvoiceKey'?digest(i[k]):id(i[k]);return out;}
 function taskFields(i){const out={};if(i.project!==undefined)out.project=text(i.project,200);if(i.sourceLink!==undefined)out.sourceLink=digest(i.sourceLink);return out;}
 function source(i){if(!i||typeof i!=='object')throw Error('Ongeldige urenbron.');return {id:id(i.id),batchId:id(i.batchId),signature:digest(i.signature),date:date(i.date),client:text(i.client,200,true),project:text(i.project,200,true),description:text(i.description,2000,true),minutes:integer(i.minutes,1,1440),rateCents:integer(i.rateCents,1,100000000),vat:vat(i.vat)};}
 function sources(list){if(!Array.isArray(list)||!list.length||list.length>100)throw Error('Kies 1 tot 100 registraties.');const ids=new Set();return list.map(i=>{const s=source(i);if(ids.has(s.id))throw Error('Dubbele urenregistratie.');ids.add(s.id);return s;});}
 function invoiceFields(i){if(i.timeSources!==undefined){sources(i.timeSources);if(i.lines.length!==i.timeSources.length)throw Error('Het aantal factuurregels past niet bij de overgenomen uren. Maak een aparte factuur voor ander werk.');}}
 function envelope(p,kinds){if(!p||p.format!=='gereedschapskist-overdracht'||p.version!==1||!kinds.includes(p.kind))throw Error('Kies het juiste overdrachtsbestand voor deze knop.');id(p.id);if(Boolean(p._gereedschapskistExample)!==GereedschapskistMode.example)throw Error('Open dit bestand in dezelfde werkruimte: eigen werk of voorbeelden.');return p;}
 function ready(){if(Werkstatus.hasPending())throw Error('Bewaar of sluit eerst het gewijzigde formulier.');}
 function fresh(){let raw;try{raw=GereedschapskistMode.storage.getItem(KEY)}catch{return}if(raw!==lastRaw)throw Error('Deze tool is in een ander venster gewijzigd. Herlaad eerst.');}
 function notice(message,destination){let box=document.getElementById('link-result');if(!box){box=document.createElement('section');box.id='link-result';box.className='link-result';box.setAttribute('role','status');document.querySelector('main').prepend(box);}box.replaceChildren();const p=document.createElement('p');p.textContent=message;box.append(p);if(destination){const a=document.createElement('a');a.href=paths[destination]+'?werkruimte='+(GereedschapskistMode.example?'voorbeeld':'eigen');a.target='_blank';a.rel='noopener';a.textContent='Open '+names[destination]+' →';box.append(a);}return box;}
 async function deliver(blob,name,destination,instruction){await Werkmap.ready;if(Werkmap.active){if(!await Werkmap.exportFile(blob,name))throw Error('Overdracht niet bewaard. Controleer de werkmapmelding en probeer opnieuw.');notice('Bestand bewaard in Exports bij deze tool. '+instruction,destination);}else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);notice('Download gestart. Controleer of het bestand is opgeslagen. '+instruction,destination);}return true;}
 async function send(kind,body,destination,instruction,transferId=uid()){
  const payload=GereedschapskistMode.forExport({format:'gereedschapskist-overdracht',version:1,id:transferId,kind,body});
  const stamp=new Date().toISOString().replace(/[:.]/g,'-');const name='gereedschapskist-'+(GereedschapskistMode.example?'voorbeeld-':'')+kind+'-'+stamp+'.json';
  return deliver(new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'}),name,destination,instruction);
 }
 function actions(){let bar=document.getElementById('link-actions');if(!bar){bar=document.createElement('div');bar.id='link-actions';bar.className='link-actions';document.querySelector('main').prepend(bar);}return bar;}
 function button(label,id,onClick){const b=document.createElement('button');b.type='button';b.id=id;b.textContent=label;b.onclick=async()=>{try{await onClick()}catch(e){notice(e.message)}};actions().append(b);return b;}
 function receiver(label,id,kinds,receive){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.id=id+'-file';document.body.append(input);button(label,id,()=>{ready();input.click()});input.onchange=async()=>{const file=input.files[0];input.value='';if(!file)return;try{if(file.size>2000000)throw Error('Maximaal 2 MB per overdracht.');ready();const p=envelope(JSON.parse(await file.text()),kinds);fresh();await receive(p);}catch(e){notice('Niet overgenomen: '+e.message)}};}
 function dialog(title,html,submit,label='Overnemen'){
  const d=document.createElement('dialog');d.className='link-dialog';d.id='link-dialog-'+(++dialogCount);d.innerHTML='<form><h2>'+esc(title)+'</h2>'+html+'<p class="link-error" role="status"></p><div class="link-actions"><button type="button" data-cancel>Annuleren</button><button class="primary" type="submit">'+esc(label)+'</button></div></form>';document.body.append(d);const form=d.querySelector('form');let busy=false;
  const snapshot=()=>JSON.stringify([...form.querySelectorAll('input,textarea,select')].map(x=>[x.value,x.checked]));let baseline='';
  const close=()=>{if(busy)return;if(snapshot()!==baseline&&!confirm('Je hebt onbewaarde invoer. Wil je die weggooien?'))return;d.close()};d.querySelector('[data-cancel]').onclick=close;d.oncancel=e=>{e.preventDefault();close()};d.onclose=()=>d.remove();
  form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=form.querySelector('[type=submit]');b.disabled=true;try{const result=await submit(form,d);if(result!==false)d.close();}catch(err){form.querySelector('.link-error').textContent=err.message;}finally{busy=false;b.disabled=false;}};
  const unload=e=>{if(d.open&&(busy||snapshot()!==baseline)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);d.addEventListener('close',()=>window.removeEventListener('beforeunload',unload));d.showModal();baseline=snapshot();return {dialog:d,form,resetBaseline:()=>baseline=snapshot()};
 }
 document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent='.link-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.link-result{border-left:4px solid #e32720;padding:12px 16px;margin:14px 0;background:#f4f4f4;font:14px/1.5 Arial;color:#111}.link-result p{margin:0 0 6px}.link-result a{font-weight:bold}.link-dialog{width:min(760px,calc(100% - 32px));max-height:90vh;overflow:auto;padding:24px;border:2px solid #111;background:#fff;color:#111;font:15px/1.5 Arial}.link-dialog::backdrop{background:#0008}.link-dialog h2{font-size:26px;margin:0 0 16px}.link-dialog label{display:block;margin:10px 0}.link-dialog input:not([type=checkbox]),.link-dialog textarea,.link-dialog select{width:100%;padding:8px;border:1px solid #999;font:inherit;box-sizing:border-box}.link-dialog input[type=checkbox],.link-select input{width:20px!important;height:20px;vertical-align:middle}.link-dialog .link-row{border-top:1px solid #bbb;padding:12px 0}.link-dialog .link-error{color:#b21b15}.link-select{display:inline-flex!important;align-items:center;gap:8px;font:13px Arial;margin:8px 0}.link-billing{font-size:12px;color:#595959;margin:8px 0}.link-dialog button:focus-visible,.link-dialog input:focus-visible,.link-dialog textarea:focus-visible,.link-actions button:focus-visible{outline:3px solid #e32720;outline-offset:3px}@media print{.link-actions,.link-result,.link-dialog,.link-select,.link-billing{display:none!important}}';document.head.append(style);});
 return {esc,uid,today,text,id,integer,date,rate,vat,number,key,digest,signature,euro,duration,timeFields,cashFields,taskFields,sources,invoiceFields,ready,fresh,notice,send,deliver,button,receiver,dialog,draft:k=>drafts.get(k)||{},setDraft:(k,v)=>drafts.set(k,v)};
})();
